#%RAML 1.0 NamedExample


{
                 "name":"Raju",
                 "address":"Hyderabad",
                 "role":"Associate Trainee",
                "company":"mouritech",
                "id":"220200"
              }