#%RAML 1.0
title: poc11

/address:
  get:
    responses:
      200:
        body:
          application/json:
            example:
              {            
"Address":"Mouritech Private Limited,Huda Techno Enclave,Survey   No. 64,4th Floor,SBR Surya Pearl Sector III,IT Park,Madhapur,Hitech City Main Rd,Phase 2,Opposite to Mindspace,Top of Karachi Bakery and Burger king,HITEC City,Hyderabad,Telangana 500081"
              }
              
    
 