#%RAML 1.0
title: poc14

/dwl:
  post:
    body:
      application/json:
        example:
          {
            Input : "20200909080000"
          }
    responses:
      201:
        body:
          application/json:
            example:
              {
                "Date":2020-09-09T00:00:00
              }
  